name: CICD
on:
  workflow_dispatch: null
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      run: echo "code clone from github"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
      run: echo "DOcker Container build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test code
      run: echo "Test code successfully"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
      run: echo "Deploy code successfully"
