name: Flask App NEW

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    env:
      DOCKERHUB_USER: ${{ vars.DOCKER_HUB_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy with Docker Compose
        run: docker compose up -d --build 