name: devsecops-pipeline

on:
  workflow_dispatch:

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  secret-scan:
    uses: ./.github/workflows/secret-scan.yml

  docker-lint:
    uses: ./.github/workflows/docker-lint.yml

  
  deploy:
    needs: [code-quality, dependency-scan, secret-scan]
    uses: ./.github/workflows/deploy-to-server.yml
    secrets: inherit

  trivy:
    needs: [deploy]
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit
