#scan dockerfilr for issuses and CVES
name: docker-lint
on:
  workflow_call:
  workflow_dispatch:
jobs:
    validate-dockerfile:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: scan dockerfile
          uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: Dockerfile