name: image-scan
on:
  workflow_call:
  workflow_dispatch:
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
jobs:
  image-scanner:
    runs-on: ubuntu-latest
    steps:
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
       - name: Run Trivy Image Scan
         uses: aquasecurity/trivy-action@0.20.0
         with:
           image-ref: ${{ vars.DOCKER_HUB_USER }}/ ${{ vars.DOCKER_HUB_USER }}/action-docker:latest
           format: 'table'
           severity: 'CRITICAL'
           exit-code: '1'