# This is the name of the workflow
name: hello

# Runs on triggers
on:
  push:
    branches: [main]

# Jobs in workflow
jobs:
  # Job 1
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to user
        run: echo "hello dosto"

      - name: Say hello to username
        run: echo "hello ${{ github.actor }}"

  # Job 2
  details:
    runs-on: ubuntu-latest

    steps:
      - name: Version of Python and Docker
        run: docker --version && python3 --version
